name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  brittle-node:
    name: brittle-node (${{ matrix.os }})
    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run lint
      - run: npm run test:node

  brittle-bare:
    name: brittle-bare (${{ matrix.os }})
    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm i -g bare
      - run: npm run lint
      - run: npm run test:bare
